#pragma once

#include <cstdint>

enum GameFunction {
  MoveLeft1,
  MoveLeft2,
  MoveRight1,
  MoveRight2,
  MoveUp1,
  MoveUp2,
  MoveDown1,
  MoveDown2,
  SelectChatAlliance,
  SelectChatGlobal,
  SelectChatPrivate,
  SelectShip1,
  SelectShip2,
  SelectShip3,
  SelectShip4,
  SelectShip5,
  SelectShip6,
  SelectShip7,
  SelectShip8,
  ShowOfficers,
  ShowCommander,
  ShowRefinery,
  ShowQTrials,
  ShowBookmarks,
  ShowExoComp,
  ShowFactions,
  ShowDaily,
  ShowAwayTeam,
  ShowMissions,
  ShowShips,
  ShowInventory,
  ShowStationInterior,
  ShoWStationExterior,
  ShowGalaxy,
  ShowSystem,
  ShowChat,
  ShowChatSide1,
  ShowChatSide2,
  ShowEvents,
  ZoomPreset1,
  ZoomPreset2,
  ZoomPreset3,
  ZoomPreset4,
  ZoomPreset5,
  ZoomIn,
  ZoomOut,
  ZoomMin,
  ZoomMax,
  ZoomReset,
  UiScaleUp,
  UiScaleDown,
  ActionPrimary,
  ActionSecondary,
  ActionView,
  ActionRecall,

  // Automatic max value
  Max
};
