// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Digit.Client.SaveSystem.proto

#include "Digit.Client.SaveSystem.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Digit {
namespace Client {
namespace SaveSystem {
        template <typename>
PROTOBUF_CONSTEXPR CloudBlob::CloudBlob(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.sections_)*/ {},
      /*decltype(_impl_.metadata_)*/ nullptr,
    } {}
struct CloudBlobDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CloudBlobDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CloudBlobDefaultTypeInternal() {}
  union {
    CloudBlob _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CloudBlobDefaultTypeInternal _CloudBlob_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR CloudSection::CloudSection(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.group_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.metadata_)*/ nullptr,
    } {}
struct CloudSectionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CloudSectionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CloudSectionDefaultTypeInternal() {}
  union {
    CloudSection _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CloudSectionDefaultTypeInternal _CloudSection_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR CloudSectionMetaData::CloudSectionMetaData(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.timestamp_)*/ nullptr,
      /*decltype(_impl_.sectiontype_)*/ 0,
    } {}
struct CloudSectionMetaDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CloudSectionMetaDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CloudSectionMetaDataDefaultTypeInternal() {}
  union {
    CloudSectionMetaData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CloudSectionMetaDataDefaultTypeInternal _CloudSectionMetaData_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR CloudBlobMetaData::CloudBlobMetaData(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.filetype_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct CloudBlobMetaDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CloudBlobMetaDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CloudBlobMetaDataDefaultTypeInternal() {}
  union {
    CloudBlobMetaData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CloudBlobMetaDataDefaultTypeInternal _CloudBlobMetaData_default_instance_;
}  // namespace SaveSystem
}  // namespace Client
}  // namespace Digit
namespace Digit {
namespace Client {
namespace SaveSystem {
bool CloudSectionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    CloudSectionType_strings[7] = {};

static const char CloudSectionType_names[] = {
    "CLOUDSECTIONTYPE_ARCHIVEDMISSIONS"
    "CLOUDSECTIONTYPE_BOOKMARKS"
    "CLOUDSECTIONTYPE_FAVOURITEDMISSIONS"
    "CLOUDSECTIONTYPE_NEWFLAGS"
    "CLOUDSECTIONTYPE_PLAYERPREFS"
    "CLOUDSECTIONTYPE_TCSLIDESHOWFLAG"
    "CLOUDSECTIONTYPE_TUTORIALSTATE"
};

static const ::google::protobuf::internal::EnumEntry CloudSectionType_entries[] =
    {
        {{&CloudSectionType_names[0], 33}, 5},
        {{&CloudSectionType_names[33], 26}, 0},
        {{&CloudSectionType_names[59], 35}, 4},
        {{&CloudSectionType_names[94], 25}, 3},
        {{&CloudSectionType_names[119], 28}, 1},
        {{&CloudSectionType_names[147], 32}, 6},
        {{&CloudSectionType_names[179], 30}, 2},
};

static const int CloudSectionType_entries_by_number[] = {
    1,  // 0 -> CLOUDSECTIONTYPE_BOOKMARKS
    4,  // 1 -> CLOUDSECTIONTYPE_PLAYERPREFS
    6,  // 2 -> CLOUDSECTIONTYPE_TUTORIALSTATE
    3,  // 3 -> CLOUDSECTIONTYPE_NEWFLAGS
    2,  // 4 -> CLOUDSECTIONTYPE_FAVOURITEDMISSIONS
    0,  // 5 -> CLOUDSECTIONTYPE_ARCHIVEDMISSIONS
    5,  // 6 -> CLOUDSECTIONTYPE_TCSLIDESHOWFLAG
};

const std::string& CloudSectionType_Name(CloudSectionType value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          CloudSectionType_entries, CloudSectionType_entries_by_number,
          7, CloudSectionType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      CloudSectionType_entries, CloudSectionType_entries_by_number, 7,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : CloudSectionType_strings[idx].get();
}

bool CloudSectionType_Parse(absl::string_view name, CloudSectionType* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      CloudSectionType_entries, 7, name, &int_value);
  if (success) {
    *value = static_cast<CloudSectionType>(int_value);
  }
  return success;
}
bool CloudFileType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    CloudFileType_strings[2] = {};

static const char CloudFileType_names[] = {
    "CLOUDFILETYPE_NORMAL"
    "CLOUDFILETYPE_STARTUP"
};

static const ::google::protobuf::internal::EnumEntry CloudFileType_entries[] =
    {
        {{&CloudFileType_names[0], 20}, 1},
        {{&CloudFileType_names[20], 21}, 0},
};

static const int CloudFileType_entries_by_number[] = {
    1,  // 0 -> CLOUDFILETYPE_STARTUP
    0,  // 1 -> CLOUDFILETYPE_NORMAL
};

const std::string& CloudFileType_Name(CloudFileType value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          CloudFileType_entries, CloudFileType_entries_by_number,
          2, CloudFileType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      CloudFileType_entries, CloudFileType_entries_by_number, 2,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : CloudFileType_strings[idx].get();
}

bool CloudFileType_Parse(absl::string_view name, CloudFileType* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      CloudFileType_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<CloudFileType>(int_value);
  }
  return success;
}
// ===================================================================

class CloudBlob::_Internal {
 public:
  using HasBits = decltype(std::declval<CloudBlob>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CloudBlob, _impl_._has_bits_);
  static const ::Digit::Client::SaveSystem::CloudBlobMetaData& metadata(const CloudBlob* msg);
  static void set_has_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::Digit::Client::SaveSystem::CloudBlobMetaData& CloudBlob::_Internal::metadata(const CloudBlob* msg) {
  return *msg->_impl_.metadata_;
}
CloudBlob::CloudBlob(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Digit.Client.SaveSystem.CloudBlob)
}
CloudBlob::CloudBlob(const CloudBlob& from) : ::google::protobuf::MessageLite() {
  CloudBlob* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.sections_){from._impl_.sections_},
      decltype(_impl_.metadata_){nullptr},
  };
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.metadata_ = new ::Digit::Client::SaveSystem::CloudBlobMetaData(*from._impl_.metadata_);
  }

  // @@protoc_insertion_point(copy_constructor:Digit.Client.SaveSystem.CloudBlob)
}
inline void CloudBlob::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.sections_){arena},
      decltype(_impl_.metadata_){nullptr},
  };
}
CloudBlob::~CloudBlob() {
  // @@protoc_insertion_point(destructor:Digit.Client.SaveSystem.CloudBlob)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void CloudBlob::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.sections_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.metadata_;
}
void CloudBlob::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CloudBlob::Clear() {
// @@protoc_insertion_point(message_clear_start:Digit.Client.SaveSystem.CloudBlob)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_sections()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.metadata_ != nullptr);
    _impl_.metadata_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* CloudBlob::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> CloudBlob::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CloudBlob, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CloudBlob_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // repeated .Digit.Client.SaveSystem.CloudSection sections = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(CloudBlob, _impl_.sections_)}},
    // .Digit.Client.SaveSystem.CloudBlobMetaData metadata = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CloudBlob, _impl_.metadata_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Digit.Client.SaveSystem.CloudBlobMetaData metadata = 1;
    {PROTOBUF_FIELD_OFFSET(CloudBlob, _impl_.metadata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .Digit.Client.SaveSystem.CloudSection sections = 2;
    {PROTOBUF_FIELD_OFFSET(CloudBlob, _impl_.sections_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Digit::Client::SaveSystem::CloudBlobMetaData>()},
    {::_pbi::TcParser::GetTable<::Digit::Client::SaveSystem::CloudSection>()},
  }}, {{
  }},
};

::uint8_t* CloudBlob::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Digit.Client.SaveSystem.CloudBlob)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .Digit.Client.SaveSystem.CloudBlobMetaData metadata = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::metadata(this),
        _Internal::metadata(this).GetCachedSize(), target, stream);
  }

  // repeated .Digit.Client.SaveSystem.CloudSection sections = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_sections_size()); i < n; i++) {
    const auto& repfield = this->_internal_sections().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Digit.Client.SaveSystem.CloudBlob)
  return target;
}

::size_t CloudBlob::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Digit.Client.SaveSystem.CloudBlob)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Digit.Client.SaveSystem.CloudSection sections = 2;
  total_size += 1UL * this->_internal_sections_size();
  for (const auto& msg : this->_internal_sections()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // .Digit.Client.SaveSystem.CloudBlobMetaData metadata = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.metadata_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CloudBlob::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CloudBlob*>(
      &from));
}

void CloudBlob::MergeFrom(const CloudBlob& from) {
  CloudBlob* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:Digit.Client.SaveSystem.CloudBlob)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_sections()->MergeFrom(from._internal_sections());
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_metadata()->::Digit::Client::SaveSystem::CloudBlobMetaData::MergeFrom(
        from._internal_metadata());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CloudBlob::CopyFrom(const CloudBlob& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Digit.Client.SaveSystem.CloudBlob)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CloudBlob::IsInitialized() const {
  return true;
}

void CloudBlob::InternalSwap(CloudBlob* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.sections_.InternalSwap(&other->_impl_.sections_);
  swap(_impl_.metadata_, other->_impl_.metadata_);
}

std::string CloudBlob::GetTypeName() const {
  return "Digit.Client.SaveSystem.CloudBlob";
}

// ===================================================================

class CloudSection::_Internal {
 public:
  using HasBits = decltype(std::declval<CloudSection>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CloudSection, _impl_._has_bits_);
  static const ::Digit::Client::SaveSystem::CloudSectionMetaData& metadata(const CloudSection* msg);
  static void set_has_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::Digit::Client::SaveSystem::CloudSectionMetaData& CloudSection::_Internal::metadata(const CloudSection* msg) {
  return *msg->_impl_.metadata_;
}
CloudSection::CloudSection(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Digit.Client.SaveSystem.CloudSection)
}
CloudSection::CloudSection(const CloudSection& from) : ::google::protobuf::MessageLite() {
  CloudSection* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.group_){},
      decltype(_impl_.metadata_){nullptr},
  };
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  _impl_.group_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.group_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_group().empty()) {
    _this->_impl_.group_.Set(from._internal_group(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.metadata_ = new ::Digit::Client::SaveSystem::CloudSectionMetaData(*from._impl_.metadata_);
  }

  // @@protoc_insertion_point(copy_constructor:Digit.Client.SaveSystem.CloudSection)
}
inline void CloudSection::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.group_){},
      decltype(_impl_.metadata_){nullptr},
  };
  _impl_.group_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.group_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
CloudSection::~CloudSection() {
  // @@protoc_insertion_point(destructor:Digit.Client.SaveSystem.CloudSection)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void CloudSection::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.group_.Destroy();
  if (this != internal_default_instance()) delete _impl_.metadata_;
}
void CloudSection::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CloudSection::Clear() {
// @@protoc_insertion_point(message_clear_start:Digit.Client.SaveSystem.CloudSection)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.group_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.metadata_ != nullptr);
    _impl_.metadata_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* CloudSection::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> CloudSection::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CloudSection, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CloudSection_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // bytes group = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CloudSection, _impl_.group_)}},
    // .Digit.Client.SaveSystem.CloudSectionMetaData metadata = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CloudSection, _impl_.metadata_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Digit.Client.SaveSystem.CloudSectionMetaData metadata = 1;
    {PROTOBUF_FIELD_OFFSET(CloudSection, _impl_.metadata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes group = 2;
    {PROTOBUF_FIELD_OFFSET(CloudSection, _impl_.group_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Digit::Client::SaveSystem::CloudSectionMetaData>()},
  }}, {{
  }},
};

::uint8_t* CloudSection::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Digit.Client.SaveSystem.CloudSection)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .Digit.Client.SaveSystem.CloudSectionMetaData metadata = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::metadata(this),
        _Internal::metadata(this).GetCachedSize(), target, stream);
  }

  // bytes group = 2;
  if (!this->_internal_group().empty()) {
    const std::string& _s = this->_internal_group();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Digit.Client.SaveSystem.CloudSection)
  return target;
}

::size_t CloudSection::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Digit.Client.SaveSystem.CloudSection)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes group = 2;
  if (!this->_internal_group().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_group());
  }

  // .Digit.Client.SaveSystem.CloudSectionMetaData metadata = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.metadata_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CloudSection::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CloudSection*>(
      &from));
}

void CloudSection::MergeFrom(const CloudSection& from) {
  CloudSection* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:Digit.Client.SaveSystem.CloudSection)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_group().empty()) {
    _this->_internal_set_group(from._internal_group());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_metadata()->::Digit::Client::SaveSystem::CloudSectionMetaData::MergeFrom(
        from._internal_metadata());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CloudSection::CopyFrom(const CloudSection& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Digit.Client.SaveSystem.CloudSection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CloudSection::IsInitialized() const {
  return true;
}

void CloudSection::InternalSwap(CloudSection* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.group_, lhs_arena,
                                       &other->_impl_.group_, rhs_arena);
  swap(_impl_.metadata_, other->_impl_.metadata_);
}

std::string CloudSection::GetTypeName() const {
  return "Digit.Client.SaveSystem.CloudSection";
}

// ===================================================================

class CloudSectionMetaData::_Internal {
 public:
  using HasBits = decltype(std::declval<CloudSectionMetaData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_._has_bits_);
  static const ::google::protobuf::Timestamp& timestamp(const CloudSectionMetaData* msg);
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Timestamp& CloudSectionMetaData::_Internal::timestamp(const CloudSectionMetaData* msg) {
  return *msg->_impl_.timestamp_;
}
void CloudSectionMetaData::clear_timestamp() {
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
CloudSectionMetaData::CloudSectionMetaData(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Digit.Client.SaveSystem.CloudSectionMetaData)
}
CloudSectionMetaData::CloudSectionMetaData(const CloudSectionMetaData& from) : ::google::protobuf::MessageLite() {
  CloudSectionMetaData* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.timestamp_){nullptr},
      decltype(_impl_.sectiontype_){},
  };
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.timestamp_ = new ::google::protobuf::Timestamp(*from._impl_.timestamp_);
  }
  _this->_impl_.sectiontype_ = from._impl_.sectiontype_;

  // @@protoc_insertion_point(copy_constructor:Digit.Client.SaveSystem.CloudSectionMetaData)
}
inline void CloudSectionMetaData::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.timestamp_){nullptr},
      decltype(_impl_.sectiontype_){0},
  };
}
CloudSectionMetaData::~CloudSectionMetaData() {
  // @@protoc_insertion_point(destructor:Digit.Client.SaveSystem.CloudSectionMetaData)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void CloudSectionMetaData::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.timestamp_;
}
void CloudSectionMetaData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CloudSectionMetaData::Clear() {
// @@protoc_insertion_point(message_clear_start:Digit.Client.SaveSystem.CloudSectionMetaData)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.timestamp_ != nullptr);
    _impl_.timestamp_->Clear();
  }
  _impl_.sectiontype_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* CloudSectionMetaData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> CloudSectionMetaData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CloudSectionMetaData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // .Digit.Client.SaveSystem.CloudSectionType sectionType = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_.sectiontype_)}},
    // .google.protobuf.Timestamp timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Digit.Client.SaveSystem.CloudSectionType sectionType = 2;
    {PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_.sectiontype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
  }},
};

::uint8_t* CloudSectionMetaData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Digit.Client.SaveSystem.CloudSectionMetaData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp timestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // .Digit.Client.SaveSystem.CloudSectionType sectionType = 2;
  if (this->_internal_sectiontype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_sectiontype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Digit.Client.SaveSystem.CloudSectionMetaData)
  return target;
}

::size_t CloudSectionMetaData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Digit.Client.SaveSystem.CloudSectionMetaData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.timestamp_);
  }

  // .Digit.Client.SaveSystem.CloudSectionType sectionType = 2;
  if (this->_internal_sectiontype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_sectiontype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CloudSectionMetaData::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CloudSectionMetaData*>(
      &from));
}

void CloudSectionMetaData::MergeFrom(const CloudSectionMetaData& from) {
  CloudSectionMetaData* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:Digit.Client.SaveSystem.CloudSectionMetaData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  if (from._internal_sectiontype() != 0) {
    _this->_internal_set_sectiontype(from._internal_sectiontype());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CloudSectionMetaData::CopyFrom(const CloudSectionMetaData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Digit.Client.SaveSystem.CloudSectionMetaData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CloudSectionMetaData::IsInitialized() const {
  return true;
}

void CloudSectionMetaData::InternalSwap(CloudSectionMetaData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_.sectiontype_)
      + sizeof(CloudSectionMetaData::_impl_.sectiontype_)
      - PROTOBUF_FIELD_OFFSET(CloudSectionMetaData, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

std::string CloudSectionMetaData::GetTypeName() const {
  return "Digit.Client.SaveSystem.CloudSectionMetaData";
}

// ===================================================================

class CloudBlobMetaData::_Internal {
 public:
};

CloudBlobMetaData::CloudBlobMetaData(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Digit.Client.SaveSystem.CloudBlobMetaData)
}
CloudBlobMetaData::CloudBlobMetaData(const CloudBlobMetaData& from)
    : ::google::protobuf::MessageLite(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Digit.Client.SaveSystem.CloudBlobMetaData)
}
inline void CloudBlobMetaData::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.filetype_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
CloudBlobMetaData::~CloudBlobMetaData() {
  // @@protoc_insertion_point(destructor:Digit.Client.SaveSystem.CloudBlobMetaData)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void CloudBlobMetaData::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void CloudBlobMetaData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CloudBlobMetaData::Clear() {
// @@protoc_insertion_point(message_clear_start:Digit.Client.SaveSystem.CloudBlobMetaData)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filetype_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* CloudBlobMetaData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CloudBlobMetaData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CloudBlobMetaData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // .Digit.Client.SaveSystem.CloudFileType filetype = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CloudBlobMetaData, _impl_.filetype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Digit.Client.SaveSystem.CloudFileType filetype = 1;
    {PROTOBUF_FIELD_OFFSET(CloudBlobMetaData, _impl_.filetype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CloudBlobMetaData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Digit.Client.SaveSystem.CloudBlobMetaData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .Digit.Client.SaveSystem.CloudFileType filetype = 1;
  if (this->_internal_filetype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_filetype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Digit.Client.SaveSystem.CloudBlobMetaData)
  return target;
}

::size_t CloudBlobMetaData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Digit.Client.SaveSystem.CloudBlobMetaData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Digit.Client.SaveSystem.CloudFileType filetype = 1;
  if (this->_internal_filetype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_filetype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CloudBlobMetaData::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CloudBlobMetaData*>(
      &from));
}

void CloudBlobMetaData::MergeFrom(const CloudBlobMetaData& from) {
  CloudBlobMetaData* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:Digit.Client.SaveSystem.CloudBlobMetaData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_filetype() != 0) {
    _this->_internal_set_filetype(from._internal_filetype());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CloudBlobMetaData::CopyFrom(const CloudBlobMetaData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Digit.Client.SaveSystem.CloudBlobMetaData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CloudBlobMetaData::IsInitialized() const {
  return true;
}

void CloudBlobMetaData::InternalSwap(CloudBlobMetaData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.filetype_, other->_impl_.filetype_);
}

std::string CloudBlobMetaData::GetTypeName() const {
  return "Digit.Client.SaveSystem.CloudBlobMetaData";
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace SaveSystem
}  // namespace Client
}  // namespace Digit
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
