// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stfc.proto

#include "stfc.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
        template <typename>
PROTOBUF_CONSTEXPR CommanderSkillSpec::CommanderSkillSpec(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.researchid_)*/ ::int64_t{0},
      /*decltype(_impl_.groupid_)*/ 0,
      /*decltype(_impl_.sortorder_)*/ 0,
      /*decltype(_impl_.skilltype_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct CommanderSkillSpecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommanderSkillSpecDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommanderSkillSpecDefaultTypeInternal() {}
  union {
    CommanderSkillSpec _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommanderSkillSpecDefaultTypeInternal _CommanderSkillSpec_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR EntityRef::EntityRef(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.entityidstr_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.parententity_)*/ nullptr,
      /*decltype(_impl_.entityid_)*/ ::int64_t{0},
      /*decltype(_impl_.entitytype_)*/ 0,
    } {}
struct EntityRefDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EntityRefDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EntityRefDefaultTypeInternal() {}
  union {
    EntityRef _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EntityRefDefaultTypeInternal _EntityRef_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR OfficerLevelRewardsSpec::OfficerLevelRewardsSpec(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.schemaid_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.id_)*/ ::int64_t{0},
      /*decltype(_impl_.amount_)*/ 0,
      /*decltype(_impl_.level_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct OfficerLevelRewardsSpecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfficerLevelRewardsSpecDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfficerLevelRewardsSpecDefaultTypeInternal() {}
  union {
    OfficerLevelRewardsSpec _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfficerLevelRewardsSpecDefaultTypeInternal _OfficerLevelRewardsSpec_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR OfficerProgressRewardSpec::OfficerProgressRewardSpec(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.amount_)*/ {},
      /* _impl_._amount_cached_byte_size_ = */ {0},
      /*decltype(_impl_.progresstype_)*/ 0,
      /*decltype(_impl_.rank_)*/ 0,
      /*decltype(_impl_.schemaid_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct OfficerProgressRewardSpecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfficerProgressRewardSpecDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfficerProgressRewardSpecDefaultTypeInternal() {}
  union {
    OfficerProgressRewardSpec _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfficerProgressRewardSpecDefaultTypeInternal _OfficerProgressRewardSpec_default_instance_;
bool OfficerSkillType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    OfficerSkillType_strings[4] = {};

static const char OfficerSkillType_names[] = {
    "OFFICERSKILLTYPE_ALWAYSON"
    "OFFICERSKILLTYPE_ONDUTY"
    "OFFICERSKILLTYPE_SELECTABLE"
    "OFFICERSKILLTYPE_UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry OfficerSkillType_entries[] =
    {
        {{&OfficerSkillType_names[0], 25}, 1},
        {{&OfficerSkillType_names[25], 23}, 2},
        {{&OfficerSkillType_names[48], 27}, 3},
        {{&OfficerSkillType_names[75], 24}, 0},
};

static const int OfficerSkillType_entries_by_number[] = {
    3,  // 0 -> OFFICERSKILLTYPE_UNKNOWN
    0,  // 1 -> OFFICERSKILLTYPE_ALWAYSON
    1,  // 2 -> OFFICERSKILLTYPE_ONDUTY
    2,  // 3 -> OFFICERSKILLTYPE_SELECTABLE
};

const std::string& OfficerSkillType_Name(OfficerSkillType value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          OfficerSkillType_entries, OfficerSkillType_entries_by_number,
          4, OfficerSkillType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      OfficerSkillType_entries, OfficerSkillType_entries_by_number, 4,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : OfficerSkillType_strings[idx].get();
}

bool OfficerSkillType_Parse(absl::string_view name, OfficerSkillType* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      OfficerSkillType_entries, 4, name, &int_value);
  if (success) {
    *value = static_cast<OfficerSkillType>(int_value);
  }
  return success;
}
bool EntityType_IsValid(int value) {
  switch (value) {
    case 0:
    case 73015892:
    case 232004982:
    case 859804212:
    case 1211023646:
    case 1794481137:
    case 2100681965:
    case 2129559302:
      return true;
    default:
      return false;
  }
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    EntityType_strings[8] = {};

static const char EntityType_names[] = {
    "ENTITYTYPE_ALLIANCE"
    "ENTITYTYPE_DEPLOYEDFLEET"
    "ENTITYTYPE_INVALID"
    "ENTITYTYPE_NPC"
    "ENTITYTYPE_OFFICER"
    "ENTITYTYPE_PLAYER"
    "ENTITYTYPE_SHIP"
    "ENTITYTYPE_SYSTEM"
};

static const ::google::protobuf::internal::EnumEntry EntityType_entries[] =
    {
        {{&EntityType_names[0], 19}, 1794481137},
        {{&EntityType_names[19], 24}, 2129559302},
        {{&EntityType_names[43], 18}, 0},
        {{&EntityType_names[61], 14}, 2100681965},
        {{&EntityType_names[75], 18}, 1211023646},
        {{&EntityType_names[93], 17}, 859804212},
        {{&EntityType_names[110], 15}, 73015892},
        {{&EntityType_names[125], 17}, 232004982},
};

static const int EntityType_entries_by_number[] = {
    2,  // 0 -> ENTITYTYPE_INVALID
    6,  // 73015892 -> ENTITYTYPE_SHIP
    7,  // 232004982 -> ENTITYTYPE_SYSTEM
    5,  // 859804212 -> ENTITYTYPE_PLAYER
    4,  // 1211023646 -> ENTITYTYPE_OFFICER
    0,  // 1794481137 -> ENTITYTYPE_ALLIANCE
    3,  // 2100681965 -> ENTITYTYPE_NPC
    1,  // 2129559302 -> ENTITYTYPE_DEPLOYEDFLEET
};

const std::string& EntityType_Name(EntityType value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          EntityType_entries, EntityType_entries_by_number,
          8, EntityType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      EntityType_entries, EntityType_entries_by_number, 8,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : EntityType_strings[idx].get();
}

bool EntityType_Parse(absl::string_view name, EntityType* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EntityType_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<EntityType>(int_value);
  }
  return success;
}
bool OfficerProgressType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    OfficerProgressType_strings[3] = {};

static const char OfficerProgressType_names[] = {
    "OFFICERPROGRESSTYPE_LEVELUP"
    "OFFICERPROGRESSTYPE_RANKUP"
    "OFFICERPROGRESSTYPE_UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry OfficerProgressType_entries[] =
    {
        {{&OfficerProgressType_names[0], 27}, 1},
        {{&OfficerProgressType_names[27], 26}, 2},
        {{&OfficerProgressType_names[53], 27}, 0},
};

static const int OfficerProgressType_entries_by_number[] = {
    2,  // 0 -> OFFICERPROGRESSTYPE_UNKNOWN
    0,  // 1 -> OFFICERPROGRESSTYPE_LEVELUP
    1,  // 2 -> OFFICERPROGRESSTYPE_RANKUP
};

const std::string& OfficerProgressType_Name(OfficerProgressType value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          OfficerProgressType_entries, OfficerProgressType_entries_by_number,
          3, OfficerProgressType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      OfficerProgressType_entries, OfficerProgressType_entries_by_number, 3,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : OfficerProgressType_strings[idx].get();
}

bool OfficerProgressType_Parse(absl::string_view name, OfficerProgressType* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      OfficerProgressType_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<OfficerProgressType>(int_value);
  }
  return success;
}
// ===================================================================

class CommanderSkillSpec::_Internal {
 public:
};

CommanderSkillSpec::CommanderSkillSpec(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CommanderSkillSpec)
}
CommanderSkillSpec::CommanderSkillSpec(const CommanderSkillSpec& from)
    : ::google::protobuf::MessageLite(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CommanderSkillSpec)
}
inline void CommanderSkillSpec::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.researchid_){::int64_t{0}},
      decltype(_impl_.groupid_){0},
      decltype(_impl_.sortorder_){0},
      decltype(_impl_.skilltype_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
CommanderSkillSpec::~CommanderSkillSpec() {
  // @@protoc_insertion_point(destructor:CommanderSkillSpec)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void CommanderSkillSpec::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void CommanderSkillSpec::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void CommanderSkillSpec::Clear() {
// @@protoc_insertion_point(message_clear_start:CommanderSkillSpec)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.researchid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.skilltype_) -
      reinterpret_cast<char*>(&_impl_.researchid_)) + sizeof(_impl_.skilltype_));
  _internal_metadata_.Clear<std::string>();
}

const char* CommanderSkillSpec::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> CommanderSkillSpec::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CommanderSkillSpec_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // .OfficerSkillType skillType = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.skilltype_)}},
    // int64 researchId = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.researchid_)}},
    // int32 groupId = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.groupid_)}},
    // int32 sortOrder = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.sortorder_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 researchId = 1;
    {PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.researchid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int32 groupId = 2;
    {PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.groupid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 sortOrder = 3;
    {PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.sortorder_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .OfficerSkillType skillType = 4;
    {PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.skilltype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CommanderSkillSpec::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommanderSkillSpec)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 researchId = 1;
  if (this->_internal_researchid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_researchid(), target);
  }

  // int32 groupId = 2;
  if (this->_internal_groupid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_groupid(), target);
  }

  // int32 sortOrder = 3;
  if (this->_internal_sortorder() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_sortorder(), target);
  }

  // .OfficerSkillType skillType = 4;
  if (this->_internal_skilltype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        4, this->_internal_skilltype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommanderSkillSpec)
  return target;
}

::size_t CommanderSkillSpec::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CommanderSkillSpec)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 researchId = 1;
  if (this->_internal_researchid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_researchid());
  }

  // int32 groupId = 2;
  if (this->_internal_groupid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_groupid());
  }

  // int32 sortOrder = 3;
  if (this->_internal_sortorder() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_sortorder());
  }

  // .OfficerSkillType skillType = 4;
  if (this->_internal_skilltype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_skilltype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CommanderSkillSpec::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CommanderSkillSpec*>(
      &from));
}

void CommanderSkillSpec::MergeFrom(const CommanderSkillSpec& from) {
  CommanderSkillSpec* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:CommanderSkillSpec)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_researchid() != 0) {
    _this->_internal_set_researchid(from._internal_researchid());
  }
  if (from._internal_groupid() != 0) {
    _this->_internal_set_groupid(from._internal_groupid());
  }
  if (from._internal_sortorder() != 0) {
    _this->_internal_set_sortorder(from._internal_sortorder());
  }
  if (from._internal_skilltype() != 0) {
    _this->_internal_set_skilltype(from._internal_skilltype());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CommanderSkillSpec::CopyFrom(const CommanderSkillSpec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CommanderSkillSpec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CommanderSkillSpec::IsInitialized() const {
  return true;
}

void CommanderSkillSpec::InternalSwap(CommanderSkillSpec* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.skilltype_)
      + sizeof(CommanderSkillSpec::_impl_.skilltype_)
      - PROTOBUF_FIELD_OFFSET(CommanderSkillSpec, _impl_.researchid_)>(
          reinterpret_cast<char*>(&_impl_.researchid_),
          reinterpret_cast<char*>(&other->_impl_.researchid_));
}

std::string CommanderSkillSpec::GetTypeName() const {
  return "CommanderSkillSpec";
}

// ===================================================================

class EntityRef::_Internal {
 public:
  using HasBits = decltype(std::declval<EntityRef>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(EntityRef, _impl_._has_bits_);
  static const ::EntityRef& parententity(const EntityRef* msg);
  static void set_has_parententity(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::EntityRef& EntityRef::_Internal::parententity(const EntityRef* msg) {
  return *msg->_impl_.parententity_;
}
EntityRef::EntityRef(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EntityRef)
}
EntityRef::EntityRef(const EntityRef& from) : ::google::protobuf::MessageLite() {
  EntityRef* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.entityidstr_){},
      decltype(_impl_.parententity_){nullptr},
      decltype(_impl_.entityid_){},
      decltype(_impl_.entitytype_){},
  };
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  _impl_.entityidstr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.entityidstr_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_entityidstr().empty()) {
    _this->_impl_.entityidstr_.Set(from._internal_entityidstr(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.parententity_ = new ::EntityRef(*from._impl_.parententity_);
  }
  ::memcpy(&_impl_.entityid_, &from._impl_.entityid_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.entitytype_) -
    reinterpret_cast<char*>(&_impl_.entityid_)) + sizeof(_impl_.entitytype_));

  // @@protoc_insertion_point(copy_constructor:EntityRef)
}
inline void EntityRef::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.entityidstr_){},
      decltype(_impl_.parententity_){nullptr},
      decltype(_impl_.entityid_){::int64_t{0}},
      decltype(_impl_.entitytype_){0},
  };
  _impl_.entityidstr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.entityidstr_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
EntityRef::~EntityRef() {
  // @@protoc_insertion_point(destructor:EntityRef)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void EntityRef::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.entityidstr_.Destroy();
  if (this != internal_default_instance()) delete _impl_.parententity_;
}
void EntityRef::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void EntityRef::Clear() {
// @@protoc_insertion_point(message_clear_start:EntityRef)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entityidstr_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.parententity_ != nullptr);
    _impl_.parententity_->Clear();
  }
  ::memset(&_impl_.entityid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.entitytype_) -
      reinterpret_cast<char*>(&_impl_.entityid_)) + sizeof(_impl_.entitytype_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* EntityRef::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 29, 2> EntityRef::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EntityRef, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_EntityRef_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // .EntityRef parentEntity = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.parententity_)}},
    // int64 entityId = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entityid_)}},
    // string entityIdStr = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entityidstr_)}},
    // .EntityType entityType = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entitytype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 entityId = 1;
    {PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entityid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string entityIdStr = 2;
    {PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entityidstr_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .EntityType entityType = 3;
    {PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entitytype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .EntityRef parentEntity = 4;
    {PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.parententity_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::EntityRef>()},
  }}, {{
    "\11\0\13\0\0\0\0\0"
    "EntityRef"
    "entityIdStr"
  }},
};

::uint8_t* EntityRef::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:EntityRef)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 entityId = 1;
  if (this->_internal_entityid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_entityid(), target);
  }

  // string entityIdStr = 2;
  if (!this->_internal_entityidstr().empty()) {
    const std::string& _s = this->_internal_entityidstr();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EntityRef.entityIdStr");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // .EntityType entityType = 3;
  if (this->_internal_entitytype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_entitytype(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .EntityRef parentEntity = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::parententity(this),
        _Internal::parententity(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EntityRef)
  return target;
}

::size_t EntityRef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EntityRef)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string entityIdStr = 2;
  if (!this->_internal_entityidstr().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_entityidstr());
  }

  // .EntityRef parentEntity = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.parententity_);
  }

  // int64 entityId = 1;
  if (this->_internal_entityid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_entityid());
  }

  // .EntityType entityType = 3;
  if (this->_internal_entitytype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_entitytype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EntityRef::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const EntityRef*>(
      &from));
}

void EntityRef::MergeFrom(const EntityRef& from) {
  EntityRef* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:EntityRef)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_entityidstr().empty()) {
    _this->_internal_set_entityidstr(from._internal_entityidstr());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_parententity()->::EntityRef::MergeFrom(
        from._internal_parententity());
  }
  if (from._internal_entityid() != 0) {
    _this->_internal_set_entityid(from._internal_entityid());
  }
  if (from._internal_entitytype() != 0) {
    _this->_internal_set_entitytype(from._internal_entitytype());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void EntityRef::CopyFrom(const EntityRef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EntityRef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool EntityRef::IsInitialized() const {
  return true;
}

void EntityRef::InternalSwap(EntityRef* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.entityidstr_, lhs_arena,
                                       &other->_impl_.entityidstr_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.entitytype_)
      + sizeof(EntityRef::_impl_.entitytype_)
      - PROTOBUF_FIELD_OFFSET(EntityRef, _impl_.parententity_)>(
          reinterpret_cast<char*>(&_impl_.parententity_),
          reinterpret_cast<char*>(&other->_impl_.parententity_));
}

std::string EntityRef::GetTypeName() const {
  return "EntityRef";
}

// ===================================================================

class OfficerLevelRewardsSpec::_Internal {
 public:
};

OfficerLevelRewardsSpec::OfficerLevelRewardsSpec(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OfficerLevelRewardsSpec)
}
OfficerLevelRewardsSpec::OfficerLevelRewardsSpec(const OfficerLevelRewardsSpec& from) : ::google::protobuf::MessageLite() {
  OfficerLevelRewardsSpec* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.schemaid_){},
      decltype(_impl_.id_){},
      decltype(_impl_.amount_){},
      decltype(_impl_.level_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  _impl_.schemaid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.schemaid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_schemaid().empty()) {
    _this->_impl_.schemaid_.Set(from._internal_schemaid(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.level_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.level_));

  // @@protoc_insertion_point(copy_constructor:OfficerLevelRewardsSpec)
}
inline void OfficerLevelRewardsSpec::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.schemaid_){},
      decltype(_impl_.id_){::int64_t{0}},
      decltype(_impl_.amount_){0},
      decltype(_impl_.level_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.schemaid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.schemaid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
OfficerLevelRewardsSpec::~OfficerLevelRewardsSpec() {
  // @@protoc_insertion_point(destructor:OfficerLevelRewardsSpec)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void OfficerLevelRewardsSpec::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.schemaid_.Destroy();
}
void OfficerLevelRewardsSpec::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void OfficerLevelRewardsSpec::Clear() {
// @@protoc_insertion_point(message_clear_start:OfficerLevelRewardsSpec)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.schemaid_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.level_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.level_));
  _internal_metadata_.Clear<std::string>();
}

const char* OfficerLevelRewardsSpec::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 40, 2> OfficerLevelRewardsSpec::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_OfficerLevelRewardsSpec_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // string schemaId = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.schemaid_)}},
    // int32 amount = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.amount_)}},
    // int64 id = 2;
    {::_pbi::TcParser::FastV64S1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.id_)}},
    // int32 level = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.level_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 amount = 1;
    {PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 id = 2;
    {PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int32 level = 3;
    {PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string schemaId = 4;
    {PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.schemaid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\0\0\10\0\0\0"
    "OfficerLevelRewardsSpec"
    "schemaId"
  }},
};

::uint8_t* OfficerLevelRewardsSpec::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OfficerLevelRewardsSpec)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 amount = 1;
  if (this->_internal_amount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_amount(), target);
  }

  // int64 id = 2;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_id(), target);
  }

  // int32 level = 3;
  if (this->_internal_level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_level(), target);
  }

  // string schemaId = 4;
  if (!this->_internal_schemaid().empty()) {
    const std::string& _s = this->_internal_schemaid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OfficerLevelRewardsSpec.schemaId");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OfficerLevelRewardsSpec)
  return target;
}

::size_t OfficerLevelRewardsSpec::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OfficerLevelRewardsSpec)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string schemaId = 4;
  if (!this->_internal_schemaid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_schemaid());
  }

  // int64 id = 2;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  // int32 amount = 1;
  if (this->_internal_amount() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_amount());
  }

  // int32 level = 3;
  if (this->_internal_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_level());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OfficerLevelRewardsSpec::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const OfficerLevelRewardsSpec*>(
      &from));
}

void OfficerLevelRewardsSpec::MergeFrom(const OfficerLevelRewardsSpec& from) {
  OfficerLevelRewardsSpec* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:OfficerLevelRewardsSpec)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_schemaid().empty()) {
    _this->_internal_set_schemaid(from._internal_schemaid());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_amount() != 0) {
    _this->_internal_set_amount(from._internal_amount());
  }
  if (from._internal_level() != 0) {
    _this->_internal_set_level(from._internal_level());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void OfficerLevelRewardsSpec::CopyFrom(const OfficerLevelRewardsSpec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OfficerLevelRewardsSpec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool OfficerLevelRewardsSpec::IsInitialized() const {
  return true;
}

void OfficerLevelRewardsSpec::InternalSwap(OfficerLevelRewardsSpec* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.schemaid_, lhs_arena,
                                       &other->_impl_.schemaid_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.level_)
      + sizeof(OfficerLevelRewardsSpec::_impl_.level_)
      - PROTOBUF_FIELD_OFFSET(OfficerLevelRewardsSpec, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

std::string OfficerLevelRewardsSpec::GetTypeName() const {
  return "OfficerLevelRewardsSpec";
}

// ===================================================================

class OfficerProgressRewardSpec::_Internal {
 public:
};

OfficerProgressRewardSpec::OfficerProgressRewardSpec(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OfficerProgressRewardSpec)
}
OfficerProgressRewardSpec::OfficerProgressRewardSpec(const OfficerProgressRewardSpec& from) : ::google::protobuf::MessageLite() {
  OfficerProgressRewardSpec* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.amount_){from._impl_.amount_},
      /* _impl_._amount_cached_byte_size_ = */ {0},
      decltype(_impl_.progresstype_){},
      decltype(_impl_.rank_){},
      decltype(_impl_.schemaid_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  ::memcpy(&_impl_.progresstype_, &from._impl_.progresstype_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.schemaid_) -
    reinterpret_cast<char*>(&_impl_.progresstype_)) + sizeof(_impl_.schemaid_));

  // @@protoc_insertion_point(copy_constructor:OfficerProgressRewardSpec)
}
inline void OfficerProgressRewardSpec::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.amount_){arena},
      /* _impl_._amount_cached_byte_size_ = */ {0},
      decltype(_impl_.progresstype_){0},
      decltype(_impl_.rank_){0},
      decltype(_impl_.schemaid_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
OfficerProgressRewardSpec::~OfficerProgressRewardSpec() {
  // @@protoc_insertion_point(destructor:OfficerProgressRewardSpec)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void OfficerProgressRewardSpec::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.amount_.~RepeatedField();
}
void OfficerProgressRewardSpec::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void OfficerProgressRewardSpec::Clear() {
// @@protoc_insertion_point(message_clear_start:OfficerProgressRewardSpec)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_amount()->Clear();
  ::memset(&_impl_.progresstype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.schemaid_) -
      reinterpret_cast<char*>(&_impl_.progresstype_)) + sizeof(_impl_.schemaid_));
  _internal_metadata_.Clear<std::string>();
}

const char* OfficerProgressRewardSpec::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> OfficerProgressRewardSpec::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_OfficerProgressRewardSpec_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // repeated int32 amount = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.amount_)}},
    // .OfficerProgressType progressType = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.progresstype_)}},
    // int32 rank = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.rank_)}},
    // int32 schemaId = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.schemaid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .OfficerProgressType progressType = 1;
    {PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.progresstype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 rank = 2;
    {PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.rank_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 schemaId = 3;
    {PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.schemaid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated int32 amount = 4;
    {PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.amount_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* OfficerProgressRewardSpec::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OfficerProgressRewardSpec)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .OfficerProgressType progressType = 1;
  if (this->_internal_progresstype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_progresstype(), target);
  }

  // int32 rank = 2;
  if (this->_internal_rank() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_rank(), target);
  }

  // int32 schemaId = 3;
  if (this->_internal_schemaid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_schemaid(), target);
  }

  // repeated int32 amount = 4;
  {
    int byte_size = _impl_._amount_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(4, _internal_amount(),
                                                 byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OfficerProgressRewardSpec)
  return target;
}

::size_t OfficerProgressRewardSpec::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OfficerProgressRewardSpec)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 amount = 4;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_amount())
    ;
    _impl_._amount_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // .OfficerProgressType progressType = 1;
  if (this->_internal_progresstype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_progresstype());
  }

  // int32 rank = 2;
  if (this->_internal_rank() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_rank());
  }

  // int32 schemaId = 3;
  if (this->_internal_schemaid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_schemaid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OfficerProgressRewardSpec::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const OfficerProgressRewardSpec*>(
      &from));
}

void OfficerProgressRewardSpec::MergeFrom(const OfficerProgressRewardSpec& from) {
  OfficerProgressRewardSpec* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:OfficerProgressRewardSpec)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_amount()->MergeFrom(from._internal_amount());
  if (from._internal_progresstype() != 0) {
    _this->_internal_set_progresstype(from._internal_progresstype());
  }
  if (from._internal_rank() != 0) {
    _this->_internal_set_rank(from._internal_rank());
  }
  if (from._internal_schemaid() != 0) {
    _this->_internal_set_schemaid(from._internal_schemaid());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void OfficerProgressRewardSpec::CopyFrom(const OfficerProgressRewardSpec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OfficerProgressRewardSpec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool OfficerProgressRewardSpec::IsInitialized() const {
  return true;
}

void OfficerProgressRewardSpec::InternalSwap(OfficerProgressRewardSpec* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.amount_.InternalSwap(&other->_impl_.amount_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.schemaid_)
      + sizeof(OfficerProgressRewardSpec::_impl_.schemaid_)
      - PROTOBUF_FIELD_OFFSET(OfficerProgressRewardSpec, _impl_.progresstype_)>(
          reinterpret_cast<char*>(&_impl_.progresstype_),
          reinterpret_cast<char*>(&other->_impl_.progresstype_));
}

std::string OfficerProgressRewardSpec::GetTypeName() const {
  return "OfficerProgressRewardSpec";
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
